# Generated by Django 3.1.6 on 2021-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(blank=True, max_length=20, null=True)),
                ('evolves_from', models.CharField(blank=True, max_length=50, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('sp_attack', models.IntegerField(blank=True, null=True)),
                ('sp_defense', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
